# management.security.enabled=false
# management.endpoints.env.enabled=true
# management.endpoints.web.exposure.include=*

# management:
#   endpoint:
#     env:
#       enabled: true
#     refresh:
#       enabled: true
#   endpoints:
#     web:
#       exposure:
#         include: env
management:
  endpoints:
    web:
      exposure:
        include: "*"
